kind: PersistentVolume
apiVersion: v1
metadata:
  name: helm-pv-volume
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"

